/*========== certificates (Google Drive: Certificados/Diploma) ==========*/
// generated from the public Drive folder; "id" is the Drive file id
const CERTIFICATES = [
    {"title": "Canva - Create an e-book with AI support", "provider": "Alura", "category": "design", "degree": false, "id": "1lvQyOYXCnIwtNJ4hLEC2KK53FC2Chcn1"},
    {"title": "Canva - Create digital designs for social media", "provider": "Alura", "category": "design", "degree": false, "id": "1f3h6bPu2lQUVhRQgzA6k3y-ESSF1SNCW"},
    {"title": "Canva - Creating a portfolio, CV and personal card", "provider": "Alura", "category": "design", "degree": false, "id": "1yeBZ4SCY0u6KKAIy7qxvWjcECyd-n1vc"},
    {"title": "Canva - Creating business presentations", "provider": "Alura", "category": "design", "degree": false, "id": "1ZuC3kQXEnR3OrPhUwmY9wE1Fqk1Y0NiY"},
    {"title": "Canva - Creating videos with motion graphics", "provider": "Alura", "category": "design", "degree": false, "id": "1WLx2h2lKTn5UQsI_yyW9zNvsd5dbHwgx"},
    {"title": "Canva", "provider": "Alura", "category": "design", "degree": true, "id": "1DA4lrpVE6sn8JXA4qy-mBdkyYX3Qbimr"},
    {"title": "Figma", "provider": "Alura", "category": "design", "degree": true, "id": "1pUgDOauaPkWpkHZdzYm-8co8pzcwLPwC"},
    {"title": "Figma - Interactive prototyping and animations", "provider": "Alura", "category": "design", "degree": false, "id": "1krsssMzQDFGE43XHpSsIus_pzdjPqkDo"},
    {"title": "Figma - Optimizing a digital product", "provider": "Alura", "category": "design", "degree": false, "id": "1081vdebW6tMKJ8AoPXHuaqeMyAK7vbd6"},
    {"title": "Figma - Understanding the tool", "provider": "Alura", "category": "design", "degree": false, "id": "1mGiysQUtlrN20K_j90pHPx2b992pe5kN"},
    {"title": "Career Development in UX", "provider": "Alura", "category": "design", "degree": true, "id": "1O_aKmaJzcVxv5ttJaHcIB5Em0dKlN0kV"},
    {"title": "Design - Theory and practice", "provider": "Alura", "category": "design", "degree": false, "id": "1ZNffM0wSAbqhLl0LJidDe_6CNgIlaXog"},
    {"title": "Design - Understand and know the area", "provider": "Alura", "category": "design", "degree": false, "id": "1dBbdFv37KgtRGBb217N071VTiZ8_aoEl"},
    {"title": "Portfolio in UX UI - Setting up a project", "provider": "Alura", "category": "design", "degree": false, "id": "183vFKYQLW6X5Wak940IAx8dE8CSgTlck"},
    {"title": "UX Design - Career transition in technology areas", "provider": "Alura", "category": "design", "degree": false, "id": "10qUZHLasd1xrx5DfjPSGNY8ulSRzdPew"},
    {"title": "Git and GitHub - Mastering code version control", "provider": "Alura", "category": "tools", "degree": false, "id": "1VewSxMdgthsE4wsOLZzx4ZbYjyR2_gyg"},
    {"title": "Git and GitHub - Sharing and collaborating on projects", "provider": "Alura", "category": "tools", "degree": false, "id": "1u-InyrcGm7ma4gKIUwpGfUZSqVsTERq1"},
    {"title": "Linux - Learn commands to perform tasks", "provider": "Alura", "category": "tools", "degree": false, "id": "1QRuI0xr-p9OEoIlYT4TZqWMNy-iQ2Em8"},
    {"title": "Windows - Using CMD", "provider": "Alura", "category": "tools", "degree": false, "id": "1W2dQgJ_eDLKhFna3ir2yb4ZEV2rp95Bu"},
    {"title": "Regular Expressions - Search, validate and replace texts", "provider": "Alura", "category": "tools", "degree": false, "id": "15O0T0wh-THUmwy1XRzCt0jJ0dY3UpP0s"},
    {"title": "Swagger - Documenting Your APIs", "provider": "Alura", "category": "tools", "degree": false, "id": "1ctoWi0xhdDwDnOMuzoAUsV19hgKzu8oD"},
    {"title": "Dart - Creating and Manipulating Variables and Lists", "provider": "Alura", "category": "flutter", "degree": false, "id": "1RO9CWM0qYYwgoBxBfbOgwOnNuXWT7fcy"},
    {"title": "Dart - Dealing with errors, exceptions and null safety", "provider": "Alura", "category": "flutter", "degree": false, "id": "1GOn0Hb0XcJqCORJ462Vf8GSRLf48-aae"},
    {"title": "Dart - Handling Exceptions and Null Safety", "provider": "Alura", "category": "flutter", "degree": false, "id": "1Uu5kiKk9acINuYNqfNcgqvJpi8_nLauq"},
    {"title": "Dart - Mastering asynchronism and creating communication with APIs", "provider": "Alura", "category": "flutter", "degree": false, "id": "1RKT70gFOu0IycvLaCeki7CVHptTCvbA5"},
    {"title": "Dart - Syntax, collections and dynamism", "provider": "Alura", "category": "flutter", "degree": false, "id": "1Bn707DjDw4Op1mRIdiV22dEi6GLlN0yU"},
    {"title": "Dart - Understanding asynchronism", "provider": "Alura", "category": "flutter", "degree": false, "id": "1ZZGHa5NiGJATImZp16gZxFp-Dggy06Kn"},
    {"title": "Dart - Understanding Object Orientation", "provider": "Alura", "category": "flutter", "degree": false, "id": "12FNnvu4ZqHlZcYsU2SrJ0BvAauN6szfP"},
    {"title": "Dart - Working with object orientation", "provider": "Alura", "category": "flutter", "degree": false, "id": "1tcmubaCIghoHUetKIxQ70UEzte7xL_kc"},
    {"title": "Dart - Working with syntax and project configuration", "provider": "Alura", "category": "flutter", "degree": false, "id": "1iA_Yo5ZQX5t7SNS2tExY9ZUHpEeXNH-S"},
    {"title": "Firebase with Flutter", "provider": "Alura", "category": "flutter", "degree": true, "id": "1uwj5R9vETkfoeW6qrGqCtjg_mEryYlcP"},
    {"title": "Dart", "provider": "Alura", "category": "flutter", "degree": true, "id": "1kWWbmg7kRpr7e_n7c6TQPFjGZcys3iPh"},
    {"title": "Flutter", "provider": "Alura", "category": "flutter", "degree": true, "id": "1KBXMWTp0P3qLJbYugQhZ1IkzZWtrMNgC"},
    {"title": "Flutter - Applying data persistence", "provider": "Alura", "category": "flutter", "degree": false, "id": "1t0YQiaKPCqUsTY9Kc8XTip48sv9Dp3lh"},
    {"title": "Flutter - Authenticating users with Authentication (Firebase)", "provider": "Alura", "category": "flutter", "degree": false, "id": "1EYKpEWfvHNi2Xw8roOMuV7zhsZOGIA2b"},
    {"title": "Flutter - Controller, navigation and states", "provider": "Alura", "category": "flutter", "degree": false, "id": "10BAMg83XJ9X0mCaFETtYRaHr-x40zuOV"},
    {"title": "Flutter - Create explicit animations in your app", "provider": "Alura", "category": "flutter", "degree": false, "id": "1vZ5lQIx0jm17XgTKIsdhU-TIsem8O_dk"},
    {"title": "Flutter - Creating an app", "provider": "Alura", "category": "flutter", "degree": false, "id": "1j1Gh3HJdcILDrOFgcyuDbMo_W3pmsk9c"},
    {"title": "Flutter - Customize your app with implicit animations", "provider": "Alura", "category": "flutter", "degree": false, "id": "1-IMxwIZxsqV6ayqYOP_ku9jPRsy4-2M3"},
    {"title": "Flutter - Evolving the application with Cloud Firestore (Firebase)", "provider": "Alura", "category": "flutter", "degree": false, "id": "1fD4Bq2pGi0yn5ZBu8XU5UvuwHMBSWDAp"},
    {"title": "Flutter - Implementing online database with Cloud Firestore (Firebase)", "provider": "Alura", "category": "flutter", "degree": false, "id": "1TGz3PogDM41NcsdvkPJTwtowUaYXFdXg"},
    {"title": "Flutter - Persistence with Flutter - Create an app with internal storage", "provider": "Alura", "category": "flutter", "degree": false, "id": "1zHmYfuVpOQYz9pCIvT1Xxq1y3i7aTCj1"},
    {"title": "Flutter - Practicing and adapting clean architecture", "provider": "Alura", "category": "flutter", "degree": false, "id": "1oHu3agdUTD3elO1yZ6YO6rHLtfYu9LjZ"},
    {"title": "Flutter - Practicing MVC architecture and pattern", "provider": "Alura", "category": "flutter", "degree": false, "id": "1QXzwyzlZ9Bg5ecfjlho6mmTQLd-2JOQ4"},
    {"title": "Flutter - Route Control and Navigation", "provider": "Alura", "category": "flutter", "degree": false, "id": "1PyXK1NodX-aJBLNfXJvGAhkUFVtsgyCA"},
    {"title": "Flutter - Saving files in the cloud with Storage (Firebase)", "provider": "Alura", "category": "flutter", "degree": false, "id": "13uEFW52dKMG713nx-lDpyTRJZtgtQ81Z"},
    {"title": "Flutter - Use animations from the Animations library", "provider": "Alura", "category": "flutter", "degree": false, "id": "1owItPqJqrjhkqhCTL4Lm93iwXXTFrZKH"},
    {"title": "Flutter - Using Getx for state management", "provider": "Alura", "category": "flutter", "degree": false, "id": "1EGjRY6VwMUFUzAZmRIaAM7x8alOHHcK5"},
    {"title": "Flutter - Widgets, Stateless, Stateful, Images and Animations", "provider": "Alura", "category": "flutter", "degree": false, "id": "1fm1mjeyEotLO1tZkK4tj3oYf-sQnjdd4"},
    {"title": "Master Swift Language", "provider": "Alura", "category": "ios", "degree": true, "id": "195X9OA3M5lqkiUl5o8uk6x5_1SIUz8C4"},
    {"title": "iOS - Auto Layout with Constraints", "provider": "Alura", "category": "ios", "degree": false, "id": "1jjNoye58R04u72RW8IzOBRRPkhYicai0"},
    {"title": "iOS - Building Your First App", "provider": "Alura", "category": "ios", "degree": false, "id": "1caDAX8RvP-9ajibOGpZZRgHP5MV2d4ko"},
    {"title": "iOS with SwiftUI - Building Components and Layouts", "provider": "Alura", "category": "ios", "degree": false, "id": "1O8nR5nB8ORiqSY1g6Eafhrg5gxaPD-pz"},
    {"title": "iOS with SwiftUI - Implementing navigation and state management", "provider": "Alura", "category": "ios", "degree": false, "id": "1sGo-AZP22QGDQLjRrNfLaiP44WRVGlGC"},
    {"title": "Swift - Understanding and practicing object orientation", "provider": "Alura", "category": "ios", "degree": false, "id": "18k3are9iXzerV_QYdMIZHAD1sjC-d8je"},
    {"title": "Swift - Understanding the language", "provider": "Alura", "category": "ios", "degree": false, "id": "1pZ7woT4Y8gCRFXSV3uRcbfElkbWV4p9O"},
    {"title": "Java", "provider": "Alura", "category": "java", "degree": true, "id": "1ubucU1RsuBjEQ5gTGVyzbaeXuXzH5RjP"},
    {"title": "Java - Applying Object Orientation", "provider": "Alura", "category": "java", "degree": false, "id": "16YUveY0ahL8yEpO27IcQPj99OGH3ldBo"},
    {"title": "Java - Consuming API, writing files and handling errors", "provider": "Alura", "category": "java", "degree": false, "id": "1i-QXm6t8gaP-Fs3NsGNkatoiSEuE0BWu"},
    {"title": "Java - Creating your first application", "provider": "Alura", "category": "java", "degree": false, "id": "1WW7lw5RKuiMEv6JlNIB0mDmmUh3_g_TZ"},
    {"title": "Java - Working with lists and collections of data", "provider": "Alura", "category": "java", "degree": false, "id": "1ShzUwrtAv512tlhPRuyCk47FQDHiXdWr"},
    {"title": "Kanban", "provider": "Alura", "category": "agile", "degree": true, "id": "1_jGrQZEei9rTT5zED9t2B_KwcvXqlQzK"},
    {"title": "Kanban - Advanced practices including portfolio management", "provider": "Alura", "category": "agile", "degree": false, "id": "1VIG_RgNaW0ecFTMQAiCGWPNjcKig__RV"},
    {"title": "Kanban - Analytics for implementation", "provider": "Alura", "category": "agile", "degree": false, "id": "1xtIjI-QH7iqxqIxpAXzC1H0ELpcacLp9"},
    {"title": "Kanban - Evolve your deliveries with metrics", "provider": "Alura", "category": "agile", "degree": false, "id": "1bmVqoyhMBIJUMnXkO7IDPIsQy-3-Magi"},
    {"title": "Kanban - Set the pace with cadences", "provider": "Alura", "category": "agile", "degree": false, "id": "1i776ozTJmIyorxSwb6HvUn8lOp9uHi8l"},
    {"title": "Kanban - Systemic implementation across multiple teams", "provider": "Alura", "category": "agile", "degree": false, "id": "1gp5eq92en0zKX_Ra3NnWHKlR_kTBWILx"},
    {"title": "Power BI - Visualizing data", "provider": "Alura", "category": "data", "degree": false, "id": "1vKSD_y88opLM23zlsO4Sqp3ZDol_ZFY1"},
    {"title": "Power BI Desktop - Building my first dashboard", "provider": "Alura", "category": "data", "degree": false, "id": "1d91WOXoczGxXfkY-vTwnTI-JegbxXtPy"},
    {"title": "React Native - AsyncStorage and Navigation", "provider": "Alura", "category": "react-native", "degree": false, "id": "1eulMKKPDm8oriD55x0Yy38fdKbj5ISlA"},
    {"title": "React Native - Authentication with Firebase", "provider": "Alura", "category": "react-native", "degree": false, "id": "1s7-CVaAIzH6M92DIAMzmVuQWmMNDJIg7"},
    {"title": "React Native - Creating menu and navigating between screens", "provider": "Alura", "category": "react-native", "degree": false, "id": "1frnuRjs0gBvb3-DUAI0o11r3Kjzsz0zf"},
    {"title": "React Native - Using Push Notification in Cloud Messaging", "provider": "Alura", "category": "react-native", "degree": false, "id": "1Lkd1tPN2gUzO6bzqMr8GDqxnpCr4jB9q"},
    {"title": "React Native part 1 - Creating native apps with JavaScript and React", "provider": "Alura", "category": "react-native", "degree": false, "id": "1q_-vjNxEqsxCMJe0frRBR62aKmO-FNqN"},
    {"title": "React Native part 2 - Improving the app with navigation and more features", "provider": "Alura", "category": "react-native", "degree": false, "id": "1RZDa6PotwbfGX2c33o1XcDEvg6eXIn2Q"},
    {"title": "Behavioral management - Enhancing self-leadership", "provider": "Alura", "category": "soft", "degree": false, "id": "107yPGfZl9zzDUQzMnLd6XZJ7dDSVSS3m"},
    {"title": "Curiosity - Exploring Persistence and Resilience for Personal Growth", "provider": "Alura", "category": "soft", "degree": false, "id": "1xp07ASUYVBFgHjOeYg3wk_Y3POpzatOo"},
    {"title": "Self-Leadership", "provider": "Alura", "category": "soft", "degree": true, "id": "1RoFsQLgnhH709BLpNcIr1BBDkjsno_kj"},
    {"title": "Self-Leadership 2", "provider": "Alura", "category": "soft", "degree": true, "id": "1tvQCKGhBm7k0p39JmYvYR2GuE6JjZj50"},
    {"title": "Skills and behavior 1", "provider": "Alura", "category": "soft", "degree": true, "id": "16vhiEkZEqbRbAUc9o6wNQpkSJfUfpUKP"},
    {"title": "Skills and behavior 2", "provider": "Alura", "category": "soft", "degree": true, "id": "1PYQpUa89wF4lDBnZgGTcTs2EaWMKnqrD"},
    {"title": "Emotional intelligence - Practices for everyday life", "provider": "Alura", "category": "soft", "degree": false, "id": "13Wu07Wxt7TdxWYBHFqTYwSvM8pmqLg3M"},
    {"title": "Imposter Syndrome - Recognize your success and results", "provider": "Alura", "category": "soft", "degree": false, "id": "1H1iz0OhxB41BJSzLm24O8NE5emPpb8mf"},
    {"title": "Interpersonal relationship part 2 - Improve your potential", "provider": "Alura", "category": "soft", "degree": false, "id": "1AdktX8CcLOBGoFjx1Dpa33YSIqNTFsZn"},
    {"title": "Interpersonal relationships- Learn to deal better with yourself and with others", "provider": "Alura", "category": "soft", "degree": false, "id": "1YIg0hWrBliMGyeEtnn4RGJjg93ltIJtm"},
    {"title": "LinkedIn Page - Improving digital presence", "provider": "Alura", "category": "soft", "degree": false, "id": "1ZXoSfKfK3WB_yalsgcSZuX7C_U2J2TM_"},
    {"title": "Personal Branding - How to use your Personal Brand to benefit your career", "provider": "Alura", "category": "soft", "degree": false, "id": "1N7UJlGDj0DfmkQ6pdYrgsUZijXDO3z1M"},
    {"title": "Principles of Teamwork - Collaborative relationships", "provider": "Alura", "category": "soft", "degree": false, "id": "1vaqdLQhIOuAU8I1CRTsbCk6eipMEBq4z"},
    {"title": "Self Leadership - Corporate Integrity - Ethical Decision Making in Business Environments", "provider": "Alura", "category": "soft", "degree": false, "id": "11Beial-8PYTEF2l-sQ8FlCxeCO3SyYC2"},
    {"title": "Self Leadership - Emotional intelligence - Increase your leadership potential", "provider": "Alura", "category": "soft", "degree": false, "id": "1GDHJ_Z3bQrt-2BBxJuSqDpr3jphL5wea"},
    {"title": "Self Leadership - Growth mindset - Enhancing your career", "provider": "Alura", "category": "soft", "degree": false, "id": "1dWHpeGYmipC5ISb287nXkm1aDkp5cPEQ"},
    {"title": "Self Leadership - Positive psychology - Authentic leadership from personal strengths", "provider": "Alura", "category": "soft", "degree": false, "id": "1H1PIBriAJtQ3zzjvehrwoMoCwueeFFX8"},
    {"title": "Self Leadership - Stress Management - Optimize Your Leadership", "provider": "Alura", "category": "soft", "degree": false, "id": "1-ScFAFq9Ibn4WNT9Mdch085V-IqCS9Jn"},
    {"title": "Self-leadership - Planning personal development", "provider": "Alura", "category": "soft", "degree": false, "id": "1UCTohJerjxLsWED6hoV30KSSTcbrxmUD"},
    {"title": "Strengths part 1 - Discover yours and learn to manage them", "provider": "Alura", "category": "soft", "degree": false, "id": "1HKb8F0MX_ZU8KQP0gGeu5jkqJL8-0ONk"},
    {"title": "Strengths part 2 - Skills and competencies", "provider": "Alura", "category": "soft", "degree": false, "id": "1L_9HfGUb75rYsBzI409Q1Cnd7juUCuY0"},
    {"title": "Stress part 1 - Seeking quality of life", "provider": "Alura", "category": "soft", "degree": false, "id": "1WIK2CD3gIHKczAx0DqpHv7tT-q5QlXzn"},
    {"title": "Stress part 2 - Balance your lifestyle", "provider": "Alura", "category": "soft", "degree": false, "id": "1olvfNu3ip3n6sDkgbqLqH1JRKuTf7pts"},
    {"title": "Assertive Communication - Reducing conflicts and frustrations", "provider": "Alura", "category": "soft", "degree": false, "id": "1pcdMd_nyXvWCeZ-tEmo9bkXadObmJB27"},
    {"title": "Communication - How to express yourself well and be understood", "provider": "Alura", "category": "soft", "degree": false, "id": "1kB0oP6jCWYoKFKDRS97UKh_czHlEyA3G"},
    {"title": "Communication", "provider": "Alura", "category": "soft", "degree": true, "id": "1W8RNWy3LaknaZYd91RdMz0h6QKzAh9ly"},
    {"title": "Effective feedback - Using tools for transformative communication", "provider": "Alura", "category": "soft", "degree": false, "id": "1E7woXRFRQDftZqaH8in8NvyJh2P2EaE_"},
    {"title": "Non-Violent Communication - Awareness to act", "provider": "Alura", "category": "soft", "degree": false, "id": "1Ye92PD2ZLxofY1GZtikIzhBH5ylxDCCk"},
    {"title": "Non-Violent Communication Part 2 - Maintaining Empathy", "provider": "Alura", "category": "soft", "degree": false, "id": "1elhi53YDPicNHahZwiXrSIhFhCZT3co0"},
    {"title": "Public Speaking - Capture your audience’s attention", "provider": "Alura", "category": "soft", "degree": false, "id": "1sMpVIj3I2nvFha9TJrxoLokgfnSr5xZw"},
    {"title": "Public Speaking - Overcome Challenges with Confidence", "provider": "Alura", "category": "soft", "degree": false, "id": "18JqcRe2YilOoJUI9UgU1PvgUUGh4IdWb"},
    {"title": "Applied Creativity - Improving the creative process in the job market", "provider": "Alura", "category": "soft", "degree": false, "id": "1h_SjM74TcfW8S38TD6WFE9TlRolKQTxn"},
    {"title": "Creativity - Curiosity, persistence and resilience, from idea to action", "provider": "Alura", "category": "soft", "degree": false, "id": "1hPJ1fUlgoVsD7_BzgRXvrQ8tKAwzJkUf"},
    {"title": "Creativity - Leverage your motivations", "provider": "Alura", "category": "soft", "degree": false, "id": "1w1u9h4twqzC1cwOwoQhLOwrs_v2iH9Th"},
    {"title": "Creativity and Adequacy - Learning and improving a creative process", "provider": "Alura", "category": "soft", "degree": false, "id": "1K_f69-o96Mhbdo886Cdqy1hauDpOEYtU"},
    {"title": "Creativity", "provider": "Alura", "category": "soft", "degree": true, "id": "1ehm8lp4hfUlg5XBoxm2n_zHHA84lt-li"},
    {"title": "Creativity 2", "provider": "Alura", "category": "soft", "degree": true, "id": "1tQnXgmarlRtPxb5tjsPUPUIMLXX3wE-w"},
    {"title": "Creativity 3", "provider": "Alura", "category": "soft", "degree": true, "id": "19qaH-Ibg1htuoRO2MVllWIKbVs6PnB7e"},
    {"title": "Storytelling - Business vision and personal development", "provider": "Alura", "category": "soft", "degree": false, "id": "1YOVnSXrIo94034TSRIEPuKj8twPUyOlj"},
    {"title": "Agile Management - Exploring agility concepts", "provider": "Alura", "category": "agile", "degree": false, "id": "1cxuNsQqRttcbeV-rhDPfQUxvFvMAv0uO"},
    {"title": "Agile Management - Process Management for Agility", "provider": "Alura", "category": "agile", "degree": false, "id": "1ZeqG5IfdwioOsj0yDBotJ7XWE8eFVuO1"},
    {"title": "Agile Product Management", "provider": "Alura", "category": "agile", "degree": false, "id": "1xSVu9Y-mRBXXhQCww-RjnqFjACdxmxn_"},
    {"title": "Culture and Agile Methods - Pillars for advanced immersion", "provider": "Alura", "category": "agile", "degree": false, "id": "1Tp9qUl8UakjPzJIZw1WxZz12kPLKBZGL"},
    {"title": "Agile Project Management 1", "provider": "Alura", "category": "agile", "degree": true, "id": "1ovn_2ujasuYLzYIzzQl_GkxDKRuYL9aD"},
    {"title": "Agile Project Management 2", "provider": "Alura", "category": "agile", "degree": true, "id": "1g08zlH9wjIx7w3HPxXKvSK7SAPcAnHJT"},
    {"title": "Agility", "provider": "Alura", "category": "agile", "degree": true, "id": "1KmmyZsIPdK99SQLlQb_8Tas9Mw64Kq68"},
    {"title": "Digital & Agile Thinking", "provider": "Alura", "category": "agile", "degree": true, "id": "1o0G4S-2dpj7JFbhpfLxiKnwsAcAPhg9-"},
    {"title": "Lean-Agile - Expand horizons for the entire organization", "provider": "Alura", "category": "agile", "degree": false, "id": "1g0Yu88oO2A2CzDc9jnfRCv-boelc6YVB"},
    {"title": "Management 3.0 - Manage the environment, not the people", "provider": "Alura", "category": "agile", "degree": false, "id": "1I18pCrJLsHBjMxatiDeIwmgcENHQbCK8"},
    {"title": "Productivity", "provider": "Alura", "category": "soft", "degree": true, "id": "1qw9ahD6Db0oePRMVk8YbDwi3iDH_KB-Y"},
    {"title": "Productivity - Building habits and practices", "provider": "Alura", "category": "soft", "degree": false, "id": "1f0p3kjxmEBDvHvMtEOF6l2p5BkQrq1cs"},
    {"title": "Productivity - Effectiveness Part 1 - Habits for your proactivity", "provider": "Alura", "category": "soft", "degree": false, "id": "1HCzAALdivMKW5zErz9JXicfjuE1vCLOh"},
    {"title": "Productivity - Effectiveness Part 2 - Habits for your proactivity", "provider": "Alura", "category": "soft", "degree": false, "id": "1i5S7bF5w3IfFPzKCgdyW5Q5kRtrM1Eue"},
    {"title": "Productivity - Focus, bringing more results to everyday life", "provider": "Alura", "category": "soft", "degree": false, "id": "1QkoBhMBD3zRUBuit4j9Y513_mVcinOKh"},
    {"title": "Productivity - Habits and practices for everyday life", "provider": "Alura", "category": "soft", "degree": false, "id": "1W4f8Hs3Os_T7I2fzssCqv98pAXS8AN-4"},
    {"title": "Productivity - Habits, from productivity to personal goals", "provider": "Alura", "category": "soft", "degree": false, "id": "1B_WTK_U6eGB_OFakLcXcVO-9IQkYfv7-"},
    {"title": "Productivity Part 1 - Everyday strategies", "provider": "Alura", "category": "soft", "degree": false, "id": "1OpnzXkITGUeJxBJg77tpY7OSqaAG7iKo"},
    {"title": "Productivity Part 2 - Organization and priority", "provider": "Alura", "category": "soft", "degree": false, "id": "1Mmm2X0rdAuM9g3NwclEkPF18gSdaGEKD"},
    {"title": "Technical Writing", "provider": "Alura", "category": "tools", "degree": true, "id": "1vIxlzh7zFU_iqyQjY8rjm6dRyjuStjhT"},
    {"title": "Technical Writing - Create documentation from scratch with DDLC", "provider": "Alura", "category": "tools", "degree": false, "id": "1o9UWA-TGvfSmELBWu8KEB90SCeu_oWb_"},
    {"title": "Technical Writing - Learn strategies, tools and best practices", "provider": "Alura", "category": "tools", "degree": false, "id": "1NOO9jl_3F8L-dJylivpPvjO_U83mb-vD"},
    {"title": "Cloud Experience", "provider": "", "category": "other", "degree": false, "id": "1r1e89OiEzzi66igzcIKbjTQVL1ciToYV"},
    {"title": "Lógica de programação", "provider": "SENAI", "category": "other", "degree": false, "id": "1nv_pyHhV4XVBGY_gxCAuKFSpiaKV8RGc"},
    {"title": "Mini-treinamento Pentest Mobile", "provider": "", "category": "other", "degree": false, "id": "15WM5gjjRucBpYU7T16OScwCNUxK-S8Ro"},
    {"title": "Selo Canva", "provider": "Canva", "category": "design", "degree": false, "id": "1qRgx4n5yar5-vH4AMoSXbLvdBQWio-uG"},
    {"title": "Criação de Apps Android-iOS-Web com Flutter - 5 Cursos em 1", "provider": "Udemy", "category": "flutter", "degree": false, "id": "1BirBF8J5E96uEc6KLLLt-o67kzPJ2pz9"},
    {"title": "Inteligência Artificial Algoritmos Genéticos com Python", "provider": "Udemy", "category": "data", "degree": false, "id": "1l_mqSyT7BEs3GMZZ7Dk6qV_GyvkbNBrW"},
    {"title": "React Native com Hooks e Context API - Cadastro Completo!", "provider": "Udemy", "category": "react-native", "degree": false, "id": "1B6LAYlfkOvSxQhuY1r6MOoJxg60i74P5"},
    {"title": "Introdução à linguagem CSS", "provider": "Udemy", "category": "web", "degree": false, "id": "1wV5YFqscv_j7hKBSES8TWVAkbWSXXJx4"},
    {"title": "Introdução à linguagem HTML", "provider": "Udemy", "category": "web", "degree": false, "id": "1x7wn2yBjigmh_e4qA42idoN0dT6F48Mk"},
    {"title": "Introdução ao JavaScript", "provider": "Udemy", "category": "web", "degree": false, "id": "1CGJaTjZqDD0zew_FuPu-LJ0ysrkuCH8s"},
    {"title": "Introdução ao PHP orientado a objeto", "provider": "Udemy", "category": "web", "degree": false, "id": "1vOvhXY3E_r5ZszJDJCx3u7Vg6yP2_KCo"},
    {"title": "Introdução à Criação de Sites Dinâmicos com PHP", "provider": "Udemy", "category": "web", "degree": false, "id": "1Vi17PtexQsMAfidN9UCevcCl2xx6oobq"},
    {"title": "JavaScript e jQuery para iniciantes", "provider": "Udemy", "category": "web", "degree": false, "id": "1IamOpxw6Iv46qLgGnnNELluzQnQIOSiC"},
    {"title": "Introdução ao ROS", "provider": "Udemy", "category": "other", "degree": false, "id": "1AlkgzMbGOY28aYJNwkMQk-SY7IfQPraU"},
    {"title": "Introdução ao Sistema Operacional Linux", "provider": "Udemy", "category": "tools", "degree": false, "id": "1st7spqEtaLMmkePPOUnG3GYrgsKnh8PX"},
    {"title": "Linguagem C pra iniciantes no CodeBlocks para Windows", "provider": "Udemy", "category": "tools", "degree": false, "id": "1ZCf9BF76V5I5tZqC4OZliJvAeaI3Wz8q"},
    {"title": "Shell script - Manipulando Arquivos", "provider": "Udemy", "category": "tools", "degree": false, "id": "1CPhfyHnTCPVECvP7vXHyqljenbRiVoei"},
    {"title": "Terminal Linux", "provider": "Udemy", "category": "tools", "degree": false, "id": "1FxizediyWZ1eKOBwaNusEKvLoziIeYvk"}
];
